### ISSUE TITLE
RSS Date formatting

### ISSUE THREAD

**Issue by Kamik423** [pennomi/comics#6]
In accordance with [the RSS spec](https://www.rssboard.org/rss-specification) a feed is to use the RFC 822 format. Your feed does not and thus at least my RSS reader (NetNewsWire) completely fails to parse the date. (screenshot in the dd.mm.yyyy format)

<img width="319" alt="Screen Shot 2022-06-20 at 11 20 45" src="https://user-images.githubusercontent.com/16278233/174569750-c14bf932-22ae-4a8d-a9e2-315005b8f47c.png">

The issue is in this line where you just include the date object instead of formatting it:

https://github.com/pennomi/comics/blob/175adff29017143c70962fb315402e8747a01eb2/apps/comics/templates/comics/rss.xml#L44

I don't have a lot of experience with Django but apparently [this](https://gist.github.com/pansapiens/204861/faa7c89571b59c4d731931762a93142ed31117b1) is how you format a template to this style. In regular python you'd format a `datetime` object like [this](https://stackoverflow.com/questions/3453177/convert-python-datetime-to-rfc-2822).

**Comment by romain-dartigues** [comment]
According to the [documentation](https://docs.djangoproject.com/en/4.1/ref/templates/builtins/#date), that should be:
```
{{ page.posted_at|date:"r" }}
```

**Comment by Kamik423** [comment]
I would love if this could be fixed. It is very frustrating to me that the items always show up at the bottom of my RSS feed. Especially since the change seems so small.

**Comment by pennomi** [comment]
I have added the `date:"r"` filter to the publish date. Please let me know if this resolves the issue. If not, I will try to use ISO formatting instead.

**Comment by Kamik423** [comment]
It is solved now, thank you :)
